### ISSUE TITLE
Boolean configuration is not saved properly

### ISSUE THREAD

**Issue by mmoreram** [elcodi/bamboo-admin#89]
The value always is "on".

It should send "" when is false
It should send "1" when is true

**Comment by tonipinel** [comment]
Yes, the standard behaviour is that the value is only sent if the checkbox is checked. This typically means you need to have a way of remembering what checkboxes you are expecting on the server side since not all the data comes back from the form.

The default value is always "on", this should be consistent across browsers.

This is covered in the W3C HTML 4 recommendation:

Checkboxes (and radio buttons) are on/off switches that may be toggled by the user. A switch is "on" when the control element's checked attribute is set. When a form is submitted, only "on" checkbox controls can become successful.

Of course we can add some Javascript to set this values but it think it's better not to change the standard behaviours...

**Comment by tonipinel** [comment]
Solved
